export const FILTER = "FILTER";
export const GET_DRIVERS = "GET_DRIVERS";
export const TEAM_ORIGIN_ORDER_FILTER = "TEAM_FILTER";
export const NAME_SEARCH_DRIVERS = "NAME_SEARCH_DRIVERS";
export const ORIGIN_FILTER = "ORIGIN_FILTER";
export const ORDER_FILTER = "ORDER_FILTER";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const GET_ALL_TEAMS = "GET_ALL_TEAMS"